### PR TITLE
Added https://github.com/avkonst/react-use-state-x package to the list

### PR DESCRIPTION
**Pull request by avkonst**
Please approve my pull request. I have added the library with useState-like hook, which can do all state management tasks for react app, including local complex state and global stores state. It replaced for my apps Mobx and traditional valuelink completely.

### CODE REVIEW

**Comment by aarongarciah** [comment]
Please, sort alphabetically.

**Comment by avkonst** [comment]
> Please, sort alphabetically.

ohh, yes. Fixed. Looks like I was tired.

**Comment by avkonst** [comment]
If you are happy with the correction, could you please accept it?

**Comment by aarongarciah** [comment]
Thanks!

**Pull request merged**
