### PR TITLE
Add useAttentionWithin

### PR DESCRIPTION
**Pull request by brayhoward**

### CODE REVIEW

**Comment by aarongarciah** [comment]
Can you sort it alphabetically?

**Comment by brayhoward** [comment]
Done!

**Comment by aarongarciah** [comment]
Sorry but now I see that is not an actual package, is a snippet. If you convert it into a published package I have no problem adding it!

**Comment by aarongarciah** [comment]
Closing this. If you convert it into a package we'll add it! Thanks

**Pull request closed without merging**
