### PR TITLE
Add moxystudio/react-promiseful

### PR DESCRIPTION
**Pull request by acostalima**

### CODE REVIEW

**Comment by paulobmarcos** [comment]
Awesome package, should be added :+1:

**Comment by aarongarciah** [comment]
Thanks!

**Comment by acostalima** [comment]
@aarongarciah are you aware of this repo https://github.com/glauberfc/awesome-react-hooks?

**Comment by aarongarciah** [comment]
No, first time I see it 🤔

**Comment by acostalima** [comment]
Check this out: https://twitter.com/awesome__re/status/1128226625550598145

**Comment by aarongarciah** [comment]
This repo was created by @jamiebuilds way before that one. Maybe we can add this repo to the awesome list. But if is not added, not that important IMO.

**Comment by acostalima** [comment]
Yeah, I guess we can do that. I'm not sure how awesome lists actually work but according to the tweet above it seems they have to be submitted somewhere. 🤔

**Comment by aarongarciah** [comment]
Yes, it needs to be submitted in the Awesome repo https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Pull request merged**
