### PR TITLE
docs: Add the React Hooks update Syntax episode

### PR DESCRIPTION
**Pull request by Fullchee**
Since the original Syntax episode is already there, I thought that the update episode could be added.

There's also a shorter episode that's even more recent as well

I'm not sure if it should be added as well

https://syntax.fm/show/307/hasty-treat-why-should-i-use-react-hooks

### CODE REVIEW

**Comment by Fullchee** [comment]
@aarongarciah any feedback?

**Comment by aarongarciah** [comment]
@Fullchee go for it. Which is the shorter, newer episode?

**Comment by Fullchee** [comment]
I added all 3 of them 😅 and I added their publication dates to help the reader/listener

image

**Comment by aarongarciah** [comment]
Great, thanks 😄

**Pull request merged**
