### PR TITLE
Adds 3 new hooks

### PR DESCRIPTION
**Pull request by chrisjpatty**
Hey! I've added 3 new hooks that all come from the same package called `crooks`. If you'd rather, I could just include the crooks package as its own entry, but for discoverability I separated them out into three entries.

- useLocalStorage
- useKeyboardShortcut
- useFiler

### CODE REVIEW

**Comment by chrisjpatty** [comment]
Here's a link to the [crooks](https://github.com/chrisjpatty/crooks) package.

**Comment by aarongarciah** [comment]
Up to you 😄  If you want to add the hooks separately, please sort them alphabetically.

**Comment by aarongarciah** [comment]
Hi @chrisjpatty! Have you decided to add them together or separately. Thanks!

**Comment by chrisjpatty** [comment]
Hey! Thanks for the follow-up. Crooks will likely keep growing so I'll just add a new commit here to add it to the catalogs section.

**Comment by aarongarciah** [comment]
Thanks!

**Pull request merged**
